cli:
  app_directory: apps
  base_model: apps.teams.models.BaseTeamModel
  css_framework: tailwind
  module_path: apps
  template_directory: templates
  use_teams: true
default_context:
  _pegasus_version: 2025.11.2
  api_framework: drf
  author_name: Oleksii
  bundler: vite
  ci: github_actions
  css_framework: tailwind
  database: postgres
  deploy_platform: heroku_docker
  description: The most amazing SaaS application the world has ever seen
  docker_mode: services
  docker_setup: default
  domain_name: localhost:8000
  email: oleksii.ianchuk@gmail.com
  enable_github_login: y
  enable_google_login: y
  enable_twitter_login: n
  front_end_framework: htmx
  github_username: yanchuk
  include_static_files: n
  marketing_email_platform: none
  plugins: []
  post_process: y
  project_name: tformance
  project_slug: tformance
  python_package_manager: uv
  standalone_front_end: none
  stripe_payment_mode: checkout
  subscription_billing_model: per_unit
  subscription_pricing_ui: stripe_hosted
  type_checker: none
  use_2fa: y
  use_admin_docs: n
  use_ai_rules_agents: n
  use_ai_rules_claude: y
  use_ai_rules_cursor: n
  use_ai_rules_junie: n
  use_api_auth: n
  use_api_keys: y
  use_async: y
  use_auto_reload: y
  use_celery: y
  use_cloud_media_storage: y
  use_dark_mode: y
  use_debug_toolbar: n
  use_ecommerce_example: n
  use_examples: y
  use_flowbite: y
  use_health_checks: y
  use_impersonation: y
  use_sentry: y
  use_shadcn: n
  use_subscriptions: y
  use_teams: y
  use_teams_example: y
  use_translations: n
  use_wagtail: y
  use_watchfiles: n
